export enum Genre {
  ACTION = 'action',
  ADVENTURE = 'adventure',
  COMEDY = 'comedy',
  CRIME = 'crime',
  BIOGRAPHY = 'biography',
  DOCUMENTARY = 'documentary',
  DRAMA = 'drama',
  FAMILY = 'family',
  FANTASY = 'fantasy',
  HORROR = 'horror',
  MUSICAL = 'musical',
  ROMANCE = 'romance',
  SCIFI = 'sci-fi',
  SPORTS = 'sports',
  SUSPENSE = 'suspense',
  TEEN = 'teen',
  WESTERN = 'western',
}